/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontSize: {
        'display-lg': ['84px', { lineHeight: '1.1', letterSpacing: '-0.04em' }],
        'display-md': ['56px', { lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'display-md-mobile': ['44px', { lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '1.25', letterSpacing: '-0.02em' }],
        'body-lg': ['18px', { lineHeight: '1.7' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'label-ui': ['14px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
      },
      colors: {
        'inverse-surface': '#e5e2e1',
        'secondary-fixed': '#d5e3ff',
        'primary-container': '#3ce9f5',
        secondary: '#a6c8ff',
        'on-surface': '#e5e2e1',
        'on-primary-container': '#00666c',
        'outline-variant': '#3b494a',
        background: '#131313',
        'surface-container-lowest': '#0e0e0e',
        'primary-fixed-dim': '#1edbe7',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'inverse-primary': '#00696f',
        'tertiary-container': '#45edc0',
        'surface-bright': '#3a3939',
        'on-secondary-fixed': '#001c3b',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#00513e',
        'on-primary-fixed': '#002022',
        tertiary: '#b7ffe4',
        'primary-fixed': '#76f5ff',
        'on-tertiary-container': '#006851',
        'on-tertiary': '#00382a',
        'on-secondary-container': '#002a53',
        'secondary-container': '#3892f8',
        'on-primary': '#00363a',
        'on-secondary': '#00315f',
        'surface-tint': '#1edbe7',
        'on-tertiary-fixed': '#002117',
        'on-surface-variant': '#bac9ca',
        'on-error': '#690005',
        primary: '#c3faff',
        'tertiary-fixed': '#59fcce',
        surface: '#131313',
        'on-secondary-fixed-variant': '#004786',
        'on-background': '#e5e2e1',
        'surface-container-low': '#1c1b1b',
        'surface-container-highest': '#353534',
        'surface-container-high': '#2a2a2a',
        'secondary-fixed-dim': '#a6c8ff',
        'on-primary-fixed-variant': '#004f54',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#2edfb3',
        outline: '#859395',
        'surface-dim': '#131313',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        md: '16px',
        xl: '48px',
        xs: '4px',
        unit: '8px',
        sm: '8px',
        lg: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat', 'sans-serif'],
        'code-sm': ['Courier Prime', 'monospace'],
        'display-md': ['Montserrat', 'sans-serif'],
        'label-ui': ['Inter', 'sans-serif'],
        'display-md-mobile': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
